from .rootBookmarkListAPIView import RootBookmarkListAPIView
from .rootBookmarkRetrieveDestroyAPIView import RootBookmarkRetrieveDestroyAPIView
from .workBookmarkCreateAPIView import WorkBookmarkCreateAPIView
from .workBookmarkRetrieveDestroyAPIView import WorkBookmarkRetrieveDestroyAPIView
