# Generated by Django 4.2.2 on 2023-06-30 14:38

from django.db import migrations, models
import django.db.models.deletion
import work.models.work


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('tag', '0001_initial'),
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='작업물 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작업물 생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='작업물 수정 일시')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field', verbose_name='작업물 분야')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', verbose_name='포트폴리오')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
                'db_table': 'work',
            },
        ),
        migrations.CreateModel(
            name='WorkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.tag')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=work.models.work.image_upload_path)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='work.work')),
            ],
        ),
    ]
