# Generated by Django 4.2.2 on 2023-07-07 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import work.models.work


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='작업물 고유번호')),
                ('field', models.CharField(choices=[(0, 'FRONTEND'), (1, 'HOMEPAGE'), (2, 'APPLICATION'), (3, 'GAME'), (4, 'BACKEND'), (5, 'DATA'), (6, 'WEB_MOBILE_DESIGN'), (7, 'VISUAL_DESIGN'), (8, 'LOGO_BRAND_DESIGN'), (9, 'PACKAGE_DESIGN'), (10, 'PRODUCT_DESIGN'), (11, 'CONSTRUCTION_DESIGN'), (12, 'INTERIOR_DESIGN'), (13, 'EXHIBITION_DESIGN'), (14, 'FASHION_DESIGN'), (15, 'JEWERLY_DESIGN'), (16, 'FABRIC_DESIGN'), (17, 'INDUSTRIAL_DESIGN'), (18, 'MEDIA_DESIGN'), (19, 'MOTION_GRAPHIC'), (20, 'FINE_ART')], max_length=500, verbose_name='작업 분야')),
                ('description', models.TextField(max_length=300, verbose_name='작업물 설명')),
                ('likes', models.ManyToManyField(related_name='like_works', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', verbose_name='포트폴리오')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
                'db_table': 'work',
            },
        ),
        migrations.CreateModel(
            name='WorkLike',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='작업물 댓글 고유번호')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.work')),
            ],
            options={
                'verbose_name': 'Work Like',
                'verbose_name_plural': 'Works Likes',
                'db_table': 'work like',
            },
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=work.models.work.image_upload_path)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='work.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='작업물 댓글 고유번호')),
                ('comment', models.TextField(verbose_name='댓글')),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='작업물 평점')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.work')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Comment',
                'verbose_name_plural': 'Works Comments',
                'db_table': 'work comment',
            },
        ),
    ]
