# Generated by Django 4.2.2 on 2023-07-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='field',
            field=models.CharField(choices=[(0, 'FRONTEND'), (1, 'HOMEPAGE'), (2, 'APPLICATION'), (3, 'GAME'), (4, 'BACKEND'), (5, 'DATA'), (6, 'WEB_MOBILE_DESIGN'), (7, 'VISUAL_DESIGN'), (8, 'LOGO_BRAND_DESIGN'), (9, 'PACKAGE_DESIGN'), (10, 'PRODUCT_DESIGN'), (11, 'CONSTRUCTION_DESIGN'), (12, 'INTERIOR_DESIGN'), (13, 'EXHIBITION_DESIGN'), (14, 'FASHION_DESIGN'), (15, 'JEWERLY_DESIGN'), (16, 'FABRIC_DESIGN'), (17, 'INDUSTRIAL_DESIGN'), (18, 'MEDIA_DESIGN'), (19, 'MOTION_GRAPHIC'), (20, 'FINE_ART')], max_length=500, verbose_name='작업 분야'),
        ),
    ]
