# Generated by Django 4.2.2 on 2023-06-30 14:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_image', models.ImageField(null=True, upload_to='portfolio', verbose_name='대표 이미지')),
                ('description', models.TextField(default='없음', null=True, verbose_name='포트폴리오 설명')),
                ('certification', models.CharField(default='없음', max_length=100, null=True, verbose_name='자격증')),
                ('career', models.CharField(default='없음', max_length=100, null=True, verbose_name='경력')),
                ('git', models.CharField(default='없음', max_length=100, null=True, verbose_name='깃허브 링크')),
                ('instagram', models.CharField(default='없음', max_length=100, null=True, verbose_name='인스타그램 링크')),
                ('twitter', models.CharField(default='없음', max_length=100, null=True, verbose_name='트위터 링크')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'db_table': 'portfolio',
            },
        ),
        migrations.CreateModel(
            name='PortfolioAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=10, verbose_name='기술')),
                ('mastery', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='숙련도')),
            ],
            options={
                'verbose_name': 'Portfolio Ability',
                'verbose_name_plural': 'Portfolio Abilities',
                'db_table': 'portfolio ability',
            },
        ),
        migrations.CreateModel(
            name='PortfolioComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='댓글')),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='포트폴리오 평점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='댓글 생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='댓글 수정일시')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', verbose_name='포트폴리오')),
            ],
            options={
                'verbose_name': 'Portfolio Comment',
                'verbose_name_plural': 'Portfolio Comments',
                'db_table': 'portfolio comment',
            },
        ),
    ]
