# Generated by Django 4.2.2 on 2023-07-06 09:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioability',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='포트폴리오 타임라인 고유번호'),
        ),
        migrations.CreateModel(
            name='PortfolioTimeline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='포트폴리오 타임라인 고유번호')),
                ('year', models.CharField(max_length=20, verbose_name='년도')),
                ('description', models.CharField(max_length=20, verbose_name='설명')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', verbose_name='포트폴리오')),
            ],
            options={
                'verbose_name': 'Portfolio Timeline',
                'verbose_name_plural': 'Portfolio Timelines',
                'db_table': 'portfolio timeline',
            },
        ),
    ]
