from .outsourcingCommentListCreateAPIView import OutsourcingCommentListCreateAPIView
from .outsourcingCommentRetrieveUpdateDestroyAPIView import OutsourcingCommentRetrieveUpdateDestroyAPIView
from .outsourcingContractListCreateAPIView import OutsourcingContractListCreateAPIView
from .outsourcingContractRetrieveUpdateAPIView import OutsourcingContractRetrieveUpdateAPIView
from .outsourcingListCreateAPIView import OutsourcingListCreateAPIView
from .outsourcingRetrieveUpdateAPIView import OutsourcingRetrieveUpdateAPIView
