from .outsourcingListCreateAPIView import OutsourcingListCreateAPIView
from .outsourcingRetrieveUpdateAPIView import OutsourcingRetrieveUpdateAPIView
from .outsourcingCommentListCreateAPIView import OutsourcingCommentListCreateAPIView
from .outsourcingCommentRetrieveUpdateDestroyAPIView import OutsourcingCommentRetrieveUpdateDestroyAPIView
from .outsourcingContractListCreateAPIView import OutsourcingContractListCreateAPIView
from .outsourcingCommentRetrieveUpdateDestroyAPIView import OutsourcingCommentRetrieveUpdateDestroyAPIView