from outsourcing.views.outsourcing.outsourcingRetrieveUpdateAPIView import OutsourcingRetrieveUpdateAPIView
from outsourcing.views.outsourcing_comment.outsourcingCommentListCreateAPIView import OutsourcingCommentListCreateAPIView
