# Generated by Django 4.2.2 on 2023-06-30 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outsourcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_provided', models.BooleanField(verbose_name='원본파일제공여부')),
                ('commercial_use_allowed', models.BooleanField(verbose_name='상업적이용여부')),
                ('additional_modification_allowed', models.BooleanField(verbose_name='추가수정여부')),
                ('reprocessing_allowed', models.BooleanField(verbose_name='재가공여부')),
                ('work_date', models.PositiveIntegerField(verbose_name='작업 예상일')),
                ('price', models.IntegerField(verbose_name='금액')),
                ('editable_count', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='수정가능횟수')),
                ('price_change_allowed', models.BooleanField(verbose_name='가격변동가능여부')),
                ('outsourcing_method', models.CharField(max_length=30, null=True, verbose_name='작업 방식')),
                ('promotion_text', models.TextField(verbose_name='외주 홍보글')),
            ],
            options={
                'verbose_name': 'Outsourcing',
                'verbose_name_plural': 'Outsourcing',
                'db_table': 'outsourcing',
            },
        ),
        migrations.CreateModel(
            name='OutsourcingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='댓글')),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='외주 평점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='댓글 생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='댓글 수정일시')),
                ('outsourcing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outsourcing.outsourcing', verbose_name='외주')),
            ],
            options={
                'verbose_name': 'Outsourcing Comment',
                'verbose_name_plural': 'Outsourcing Comments',
                'db_table': 'outsourcing comment',
            },
        ),
    ]
